import Foundation

/// What File ▸ Export Shader… writes for the RealityKit target (spec §23.6): a `.metal` holding
/// both `[[visible]]` functions and a `.swift` snippet that builds the material.
public enum MaterialExport {
    /// `settings.liveParameters`, narrowed to exactly the entries `bakedUniforms` itself would
    /// substitute for — **the same two conditions**, `field(for:) != nil` *and* `.type == .float`,
    /// not a filter that merely happens to agree with it. (A first version of this filter checked
    /// field existence alone: `vector.dot`'s `a` and `b` are both `.generic("T")` with `a`'s own
    /// default `.float(1)`; wiring `b` to a `float3` unifies `T` to `float3` for both, so the real
    /// layout field for `a` is `p1: float3` — but `MaterialValidation.fieldType`'s fallback resolves
    /// `a`'s *default value* rather than its resolved type and answered `.float`, so validation
    /// passed it, and the field-existence-only filter here kept it too: the header advertised `.x`,
    /// the snippet seeded `SIMD4<Float>(1.0, …)`, and the `.metal` baked `dot(float3(1.0, 1.0, 1.0),
    /// …)` — no `custom_parameter()` anywhere. `bakedUniforms`'s own `f.type == .float` gate is what
    /// actually decided this field bakes rather than substitutes; a second predicate that checked
    /// something else and merely agreed with it most of the time was the bug, not a coincidence to
    /// keep chasing case by case.)
    ///
    /// Each survivor keeps its **original** index into `settings.liveParameters` — the index
    /// `bakedUniforms` itself keys the component letter on (`EmitEnvironment.bakedUniforms`'s
    /// `live.firstIndex(of: path)`), which does not shift when an earlier entry is dropped. A path
    /// filtered out here — because nothing requests its uniform slot at all (most commonly a
    /// rewired input), or because its field is real but not a float (`vector.dot` above) — has
    /// nothing in the emitted `.metal` reading `custom_parameter()` for it either. Without this
    /// narrowing, `header` and `swiftSnippet` would still document and seed a component the export
    /// never touches: the user writes to `.x` from Swift, nothing animates, and nothing says why.
    /// Re-enumerating the *filtered* list from 0 instead of keeping the original index would be a
    /// second bug of the same shape: entry 2 surviving while entry 1 is dropped must still print
    /// `.z` (its real, unshifted position), not `.y`.
    ///
    /// The real gap `vector.dot` exposes — `fieldType` judging a generic input's *default value*
    /// rather than its *resolved* type — stays open. Closing it needs type resolution inside
    /// `MaterialValidation`, which runs before the emitter (`ShaderGenerator.swift:72`, gating
    /// generation on its errors) and so cannot borrow the emitter's own resolved types without
    /// running that pass twice per generation. This filter is the proportionate fix: it guarantees
    /// the export's three artifacts — `.metal`, header, snippet — never disagree about which
    /// component is real, even while validation can still be wrong about a generic path's type.
    private static func liveParameters(for shader: GeneratedShader, document doc: ShaderDocument) -> [(index: Int, path: ParamPath)] {
        doc.settings.liveParameters.enumerated()
            .filter { shader.layout.field(for: $0.element)?.type == .float }
            .map { (index: $0.offset, path: $0.element) }
    }

    /// `custom_parameter()`'s component for `index` in a filtered live-parameter list, `nil` past
    /// the fourth. `EmitEnvironment.liveParameterComponents` is the one spelling this and
    /// `bakedUniforms` both read.
    private static func component(_ index: Int) -> String? {
        EmitEnvironment.liveParameterComponents.indices.contains(index) ? EmitEnvironment.liveParameterComponents[index] : nil
    }

    /// The comment block prepended to the exported source: what this file is, which lighting model
    /// it was written for, every baked parameter with the node it came from, and the texture slot.
    public static func header(for shader: GeneratedShader, document doc: ShaderDocument,
                              registry: NodeRegistry) -> String {
        let name = StitchableCodegen.sanitizedName(doc.settings.exportName)
        let live = liveParameters(for: shader, document: doc)
        var lines = [
            "// RealityKit CustomMaterial \"\(name)\" — generated by MetalNodes.",
            "// Lighting model: \(doc.settings.lightingModel.rawValue)",
            "//",
            "// Parameters are baked as literals unless marked live below: a CustomMaterial exposes",
            "// one float4 and one texture, so there is no uniform buffer to read most values from.",
            "// Edit the graph and re-export to change a baked value.",
            "//",
            "// Baked parameters:",
        ]
        var any = false
        for f in shader.layout.fields {
            guard let path = f.path, !live.contains(where: { $0.path == path }) else { continue }
            any = true
            let value = ParamValues.value(for: path, in: doc, registry: registry)
                .map { ParamValues.mslLiteral($0, as: f.type) } ?? "0.0"
            lines.append("//   \(label(for: path, document: doc, registry: registry)) = \(value)")
        }
        if !any { lines.append("//   (none)") }
        if !live.isEmpty {
            // §24.6: up to four parameters read the material's own float4 instead of a literal, so
            // they can be updated from Swift (`material.custom.value`, in the paired .swift file)
            // without a re-export.
            lines.append("// Live parameters (animate via material.custom.value — spec §24.6):")
            for (index, path) in live {
                let letter = component(index) ?? "?"
                lines.append("//   .\(letter) = \(label(for: path, document: doc, registry: registry))")
            }
        }
        lines.append("// Textures:")
        if shader.textures.isEmpty {
            lines.append("//   (none)")
        } else {
            for slot in shader.textures {
                let assetName = slot.asset.flatMap { doc.settings.assets[$0]?.name } ?? "unassigned"
                lines.append("//   params.textures().custom()  \u{2190} \(assetName)")
            }
        }
        return lines.joined(separator: "\n") + "\n\n"
    }

    /// "Node title · Parameter label" for a slot, the same shape `ShaderExport` uses.
    private static func label(for path: ParamPath, document doc: ShaderDocument, registry: NodeRegistry) -> String {
        guard let nodeID = path.instancePath.first,
              let (node, nodePath) = doc.node(nodeID),
              let shape = doc.shape(of: node, in: nodePath, registry: registry) else { return path.param }
        let label = shape.input(named: path.param)?.label ?? shape.param(named: path.param)?.label ?? path.param
        return "\(node.customTitle ?? shape.title) · \(label)"
    }

    /// The Swift the reader pastes into their app.
    public static func swiftSnippet(for shader: GeneratedShader, document doc: ShaderDocument,
                                    registry: NodeRegistry) -> String {
        let name = StitchableCodegen.sanitizedName(doc.settings.exportName)
        let names = MaterialCodegen.functionNames(exportName: doc.settings.exportName)
        let hasGeometry = shader.stageFunctionNames[.geometry] != nil
        let hasTexture = !shader.textures.isEmpty
        let live = liveParameters(for: shader, document: doc)
        let hasLive = !live.isEmpty

        let makeSignature = hasTexture
            ? "static func make(texture: TextureResource? = nil) throws -> CustomMaterial {"
            : "static func make() throws -> CustomMaterial {"
        let makeCall = hasTexture ? "make(texture: texture)" : "make()"

        var s = "// \(name).swift — generated by MetalNodes. Pairs with \(name).metal.\n"
        s += "//\n"
        s += "// Add \(name).metal to the target so its functions land in the default library.\n"
        s += "import RealityKit\n"
        s += "import Metal\n\n"
        s += "enum \(name.prefix(1).uppercased() + name.dropFirst())Material {\n"
        s += "    struct NoMetalDevice: Error {}\n\n"
        s += "    /// Builds the material. Call once and reuse it — compiling shaders is not free.\n"
        if hasTexture {
            s += "    /// - Parameter texture: assigned to `custom.texture`, the slot the graph's texture sample reads.\n"
        }
        if hasLive {
            // spec §24.6: up to four parameters read `custom.value` instead of a baked literal, so
            // they can be updated from Swift — after `make()` returns, or each frame — without a
            // re-export. `make()` only seeds the starting value here; the reader owns it after that.
            s += "    ///\n"
            s += "    /// `material.custom.value` carries the live parameters below. Write to it — on the\n"
            s += "    /// material returned here, or later via the entity's `ModelComponent` — to animate\n"
            s += "    /// them without re-exporting the shader:\n"
            for (index, path) in live {
                let letter = component(index) ?? "?"
                s += "    ///   .\(letter) — \(label(for: path, document: doc, registry: registry))\n"
            }
        }
        s += "    @MainActor\n"
        s += "    \(makeSignature)\n"
        s += "        guard let device = MTLCreateSystemDefaultDevice() else {\n"
        s += "            throw NoMetalDevice()\n"
        s += "        }\n"
        s += "        let library = try device.makeDefaultLibrary(bundle: .main)\n"
        s += "        let surface = CustomMaterial.SurfaceShader(named: \"\(names.surface)\", in: library)\n"
        if hasGeometry {
            s += "        let geometry = CustomMaterial.GeometryModifier(named: \"\(names.geometry)\", in: library)\n"
        }
        func customMaterialArgs(alignedAfter prefix: String) -> String {
            let pad = String(repeating: " ", count: prefix.count)
            var lines = ["surfaceShader: surface,"]
            if hasGeometry { lines.append("geometryModifier: geometry,") }
            lines.append("lightingModel: \(doc.settings.lightingModel.swiftCase)")
            return lines.joined(separator: "\n" + pad)
        }
        if hasTexture || hasLive {
            let prefix = "        var material = try CustomMaterial("
            s += prefix + customMaterialArgs(alignedAfter: prefix) + ")\n"
            if hasTexture {
                s += "        if let texture {\n"
                s += "            material.custom.texture = .init(texture)\n"
                s += "        }\n"
            }
            if hasLive {
                // Seeded at each entry's real, unshifted index (see `liveParameters(for:document:)`)
                // so a component with no live entry reaching it — including one past `live`'s own
                // count, past the fourth — reads 0.0 rather than borrowing a neighbour's value.
                var components = Array(repeating: "0.0", count: EmitEnvironment.liveParameterComponents.count)
                for (index, path) in live where index < components.count {
                    components[index] = ParamValues.value(for: path, in: doc, registry: registry)
                        .map { ParamValues.mslLiteral($0, as: .float) } ?? "0.0"
                }
                s += "        material.custom.value = SIMD4<Float>(\(components.joined(separator: ", ")))\n"
            }
            s += "        return material\n"
        } else {
            let prefix = "        return try CustomMaterial("
            s += prefix + customMaterialArgs(alignedAfter: prefix) + ")\n"
        }
        s += "    }\n"
        if hasGeometry {
            s += "\n    /// A geometry modifier can push vertices outside the entity's original bounds,\n"
            s += "    /// and RealityKit may then cull the entity. Grow the margin to cover the largest\n"
            s += "    /// displacement your graph produces.\n"
            s += "    @MainActor\n"
            if hasTexture {
                s += "    static func apply(to entity: ModelEntity, texture: TextureResource? = nil, boundsMargin: Float = 0.5) throws {\n"
            } else {
                s += "    static func apply(to entity: ModelEntity, boundsMargin: Float = 0.5) throws {\n"
            }
            s += "        entity.model?.materials = [try \(makeCall)]\n"
            s += "        entity.model?.boundsMargin = boundsMargin\n"
            s += "    }\n"
        } else {
            s += "\n    @MainActor\n"
            if hasTexture {
                s += "    static func apply(to entity: ModelEntity, texture: TextureResource? = nil) throws {\n"
            } else {
                s += "    static func apply(to entity: ModelEntity) throws {\n"
            }
            s += "        entity.model?.materials = [try \(makeCall)]\n"
            s += "    }\n"
        }
        s += "}\n"
        return s
    }
}
