import Foundation

/// What File ▸ Export Shader… writes for the RealityKit target (spec §23.6): a `.metal` holding
/// both `[[visible]]` functions and a `.swift` snippet that builds the material.
public enum MaterialExport {
    /// The comment block prepended to the exported source: what this file is, which lighting model
    /// it was written for, every baked parameter with the node it came from, and the texture slot.
    public static func header(for shader: GeneratedShader, document doc: ShaderDocument,
                              registry: NodeRegistry) -> String {
        let name = StitchableCodegen.sanitizedName(doc.settings.exportName)
        var lines = [
            "// RealityKit CustomMaterial \"\(name)\" — generated by MetalNodes.",
            "// Lighting model: \(doc.settings.lightingModel.rawValue)",
            "//",
            "// Parameters are baked as literals: a CustomMaterial exposes one float4 and one",
            "// texture, so there is no uniform buffer to read. Edit the graph and re-export to",
            "// change a value.",
            "//",
            "// Baked parameters:",
        ]
        var any = false
        for f in shader.layout.fields {
            guard let path = f.path else { continue }
            any = true
            let value = ParamValues.value(for: path, in: doc, registry: registry)
                .map { ParamValues.mslLiteral($0, as: f.type) } ?? "0.0"
            lines.append("//   \(label(for: path, document: doc, registry: registry)) = \(value)")
        }
        if !any { lines.append("//   (none)") }
        lines.append("// Textures:")
        if shader.textures.isEmpty {
            lines.append("//   (none)")
        } else {
            for slot in shader.textures {
                let assetName = slot.asset.flatMap { doc.settings.assets[$0]?.name } ?? "unassigned"
                lines.append("//   params.textures().custom()  \u{2190} \(assetName)")
            }
        }
        return lines.joined(separator: "\n") + "\n\n"
    }

    /// "Node title · Parameter label" for a slot, the same shape `ShaderExport` uses.
    private static func label(for path: ParamPath, document doc: ShaderDocument, registry: NodeRegistry) -> String {
        guard let nodeID = path.instancePath.first,
              let (node, nodePath) = doc.node(nodeID),
              let shape = doc.shape(of: node, in: nodePath, registry: registry) else { return path.param }
        let label = shape.input(named: path.param)?.label ?? shape.param(named: path.param)?.label ?? path.param
        return "\(node.customTitle ?? shape.title) · \(label)"
    }

    /// The Swift the reader pastes into their app.
    public static func swiftSnippet(for shader: GeneratedShader, document doc: ShaderDocument,
                                    registry: NodeRegistry) -> String {
        let name = StitchableCodegen.sanitizedName(doc.settings.exportName)
        let names = MaterialCodegen.functionNames(exportName: doc.settings.exportName)
        let hasGeometry = shader.stageFunctionNames[.geometry] != nil
        let hasTexture = !shader.textures.isEmpty

        let makeSignature = hasTexture
            ? "static func make(texture: TextureResource? = nil) throws -> CustomMaterial {"
            : "static func make() throws -> CustomMaterial {"
        let makeCall = hasTexture ? "make(texture: texture)" : "make()"

        var s = "// \(name).swift — generated by MetalNodes. Pairs with \(name).metal.\n"
        s += "//\n"
        s += "// Add \(name).metal to the target so its functions land in the default library.\n"
        s += "import RealityKit\n"
        s += "import Metal\n\n"
        s += "enum \(name.prefix(1).uppercased() + name.dropFirst())Material {\n"
        s += "    struct NoMetalDevice: Error {}\n\n"
        s += "    /// Builds the material. Call once and reuse it — compiling shaders is not free.\n"
        if hasTexture {
            s += "    /// - Parameter texture: assigned to `custom.texture`, the slot the graph's texture sample reads.\n"
        }
        s += "    @MainActor\n"
        s += "    \(makeSignature)\n"
        s += "        guard let device = MTLCreateSystemDefaultDevice() else {\n"
        s += "            throw NoMetalDevice()\n"
        s += "        }\n"
        s += "        let library = try device.makeDefaultLibrary(bundle: .main)\n"
        s += "        let surface = CustomMaterial.SurfaceShader(named: \"\(names.surface)\", in: library)\n"
        if hasGeometry {
            s += "        let geometry = CustomMaterial.GeometryModifier(named: \"\(names.geometry)\", in: library)\n"
        }
        func customMaterialArgs(alignedAfter prefix: String) -> String {
            let pad = String(repeating: " ", count: prefix.count)
            var lines = ["surfaceShader: surface,"]
            if hasGeometry { lines.append("geometryModifier: geometry,") }
            lines.append("lightingModel: \(doc.settings.lightingModel.swiftCase)")
            return lines.joined(separator: "\n" + pad)
        }
        if hasTexture {
            let prefix = "        var material = try CustomMaterial("
            s += prefix + customMaterialArgs(alignedAfter: prefix) + ")\n"
            s += "        if let texture {\n"
            s += "            material.custom.texture = .init(texture)\n"
            s += "        }\n"
            s += "        return material\n"
        } else {
            let prefix = "        return try CustomMaterial("
            s += prefix + customMaterialArgs(alignedAfter: prefix) + ")\n"
        }
        s += "    }\n"
        if hasGeometry {
            s += "\n    /// A geometry modifier can push vertices outside the entity's original bounds,\n"
            s += "    /// and RealityKit may then cull the entity. Grow the margin to cover the largest\n"
            s += "    /// displacement your graph produces.\n"
            s += "    @MainActor\n"
            if hasTexture {
                s += "    static func apply(to entity: ModelEntity, texture: TextureResource? = nil, boundsMargin: Float = 0.5) throws {\n"
            } else {
                s += "    static func apply(to entity: ModelEntity, boundsMargin: Float = 0.5) throws {\n"
            }
            s += "        entity.model?.materials = [try \(makeCall)]\n"
            s += "        entity.model?.boundsMargin = boundsMargin\n"
            s += "    }\n"
        } else {
            s += "\n    @MainActor\n"
            if hasTexture {
                s += "    static func apply(to entity: ModelEntity, texture: TextureResource? = nil) throws {\n"
            } else {
                s += "    static func apply(to entity: ModelEntity) throws {\n"
            }
            s += "        entity.model?.materials = [try \(makeCall)]\n"
            s += "    }\n"
        }
        s += "}\n"
        return s
    }
}
