// matAspect.swift — generated by MetalNodes. Pairs with matAspect.metal.
//
// Add matAspect.metal to the target so its functions land in the default library.
import RealityKit
import Metal

enum MatAspectMaterial {
    struct NoMetalDevice: Error {}

    /// Builds the material. Call once and reuse it — compiling shaders is not free.
    @MainActor
    static func make() throws -> CustomMaterial {
        guard let device = MTLCreateSystemDefaultDevice() else {
            throw NoMetalDevice()
        }
        let library = try device.makeDefaultLibrary(bundle: .main)
        let surface = CustomMaterial.SurfaceShader(named: "matAspect_surface", in: library)
        return try CustomMaterial(surfaceShader: surface,
                                  lightingModel: .lit)
    }

    @MainActor
    static func apply(to entity: ModelEntity) throws {
        entity.model?.materials = [try make()]
    }
}
