// RealityKit CustomMaterial "matAspect" — generated by MetalNodes.
// Lighting model: lit
//
// Parameters are baked as literals: a CustomMaterial exposes one float4 and one
// texture, so there is no uniform buffer to read. Edit the graph and re-export to
// change a value.
//
// Baked parameters:
//   Color · Value = float4(0.2, 0.5, 0.9, 1.0)
//   Material Output · Normal = float3(0.0, 0.0, 1.0)
//   Material Output · Emissive = float4(0.0, 0.0, 0.0, 1.0)
//   Material Output · Position Offset = float3(0.0, 0.0, 0.0)
//   Material Output · Opacity = 1.0
//   Material Output · Ambient Occlusion = 1.0
//   Material Output · Specular = 0.5
// Textures:
//   (none)

#include <metal_stdlib>
#include <RealityKit/RealityKit.h>
using namespace metal;

struct G_c6d1c7bb_Out {
    float out;
};

G_c6d1c7bb_Out mn_g_Pulse_c6d1c7bb(float2 uv, float time, float2 size, float2 mouse) {
    float v0;
    v0 = time;
    float v1;
    v1 = sin(v0);
    G_c6d1c7bb_Out out;
    out.out = v1;
    return out;
}

[[visible]]
void matAspect_surface(realitykit::surface_parameters params) {
    auto surface = params.surface();
    float4 v0;
    v0 = float4(0.2, 0.5, 0.9, 1.0);
    float2 v1;
    v1 = (params.geometry().uv0() - 0.5) * (float2(1.0, 1.0) / float2(1.0, 1.0).y);
    float v2;
    float v3;
    float v4;
    v2 = float3(v1, 0.0).x;
    v3 = float3(v1, 0.0).y;
    v4 = float3(v1, 0.0).z;
    G_c6d1c7bb_Out r5 = mn_g_Pulse_c6d1c7bb(params.geometry().uv0(), params.uniforms().time(), float2(1.0, 1.0), float2(0.0, 0.0));
    float v6;
    v6 = r5.out;
    surface.set_base_color(half3(v0.rgb));
    surface.set_normal(float3(0.0, 0.0, 1.0));
    surface.set_roughness(half(v6));
    surface.set_metallic(half(v2));
    surface.set_emissive_color(half3(float4(0.0, 0.0, 0.0, 1.0).rgb));
    surface.set_opacity(half(1.0));
    surface.set_ambient_occlusion(half(1.0));
    surface.set_specular(half(0.5));
}
