// RealityKit CustomMaterial "matGroup" — generated by MetalNodes.
// Lighting model: lit
//
// Parameters are baked as literals: a CustomMaterial exposes one float4 and one
// texture, so there is no uniform buffer to read. Edit the graph and re-export to
// change a value.
//
// Baked parameters:
//   Color · Value = float4(0.2, 0.5, 0.9, 1.0)
//   Material Output · Normal = float3(0.0, 0.0, 1.0)
//   Material Output · Emissive = float4(0.0, 0.0, 0.0, 1.0)
//   Material Output · Position Offset = float3(0.0, 0.0, 0.0)
//   Material Output · Metallic = 0.0
//   Material Output · Opacity = 1.0
//   Material Output · Ambient Occlusion = 1.0
//   Material Output · Specular = 0.5
// Textures:
//   (none)

#include <metal_stdlib>
#include <RealityKit/RealityKit.h>
using namespace metal;

struct G_f367bf8a_Out {
    float out;
};

G_f367bf8a_Out mn_g_Pulse_f367bf8a(float2 uv, float time, float2 size, float2 mouse) {
    float v0;
    v0 = time;
    float v1;
    v1 = sin(v0);
    G_f367bf8a_Out out;
    out.out = v1;
    return out;
}

[[visible]]
void matGroup_surface(realitykit::surface_parameters params) {
    auto surface = params.surface();
    float4 v0;
    v0 = float4(0.2, 0.5, 0.9, 1.0);
    G_f367bf8a_Out r1 = mn_g_Pulse_f367bf8a(params.geometry().uv0(), params.uniforms().time(), float2(1.0, 1.0), float2(0.0, 0.0));
    float v2;
    v2 = r1.out;
    surface.set_base_color(half3(v0.rgb));
    surface.set_normal(float3(0.0, 0.0, 1.0));
    surface.set_roughness(half(v2));
    surface.set_metallic(half(0.0));
    surface.set_emissive_color(half3(float4(0.0, 0.0, 0.0, 1.0).rgb));
    surface.set_opacity(half(1.0));
    surface.set_ambient_occlusion(half(1.0));
    surface.set_specular(half(0.5));
}
