// RealityKit CustomMaterial "metalNodesShader" — generated by MetalNodes.
// Lighting model: lit
//
// Parameters are baked as literals: a CustomMaterial exposes one float4 and one
// texture, so there is no uniform buffer to read. Edit the graph and re-export to
// change a value.
//
// Baked parameters:
//   Color · Value = float4(0.85, 0.55, 0.25, 1.0)
//   Material Output · Normal = float3(0.0, 0.0, 1.0)
//   Material Output · Emissive = float4(0.0, 0.0, 0.0, 1.0)
//   Value Noise · Scale = 6.0
//   Material Output · Metallic = 0.0
//   Material Output · Opacity = 1.0
//   Material Output · Ambient Occlusion = 1.0
//   Material Output · Specular = 0.5
//   Float · Value = 0.06
//   Float · Value = 0.6
//   Combine XYZ · X = 0.0
//   Combine XYZ · Z = 0.0
// Textures:
//   (none)

#include <metal_stdlib>
#include <RealityKit/RealityKit.h>
using namespace metal;

float mn_hash21(float2 p) {
    p = fract(p * float2(123.34, 456.21));
    p += dot(p, p + 45.32);
    return fract(p.x * p.y);
}

float mn_valueNoise(float2 p) {
    float2 i = floor(p);
    float2 f = fract(p);
    float2 s = f * f * (3.0 - 2.0 * f);
    float a = mn_hash21(i);
    float b = mn_hash21(i + float2(1.0, 0.0));
    float c = mn_hash21(i + float2(0.0, 1.0));
    float d = mn_hash21(i + float2(1.0, 1.0));
    return mix(mix(a, b, s.x), mix(c, d, s.x), s.y);
}

[[visible]]
void metalNodesShader_surface(realitykit::surface_parameters params) {
    auto surface = params.surface();
    float4 v0;
    v0 = float4(0.85, 0.55, 0.25, 1.0);
    float v1;
    v1 = mn_valueNoise(params.geometry().uv0() * 6.0);
    surface.set_base_color(half3(v0.rgb));
    surface.set_normal(float3(0.0, 0.0, 1.0));
    surface.set_roughness(half(v1));
    surface.set_metallic(half(0.0));
    surface.set_emissive_color(half3(float4(0.0, 0.0, 0.0, 1.0).rgb));
    surface.set_opacity(half(1.0));
    surface.set_ambient_occlusion(half(1.0));
    surface.set_specular(half(0.5));
}

[[visible]]
void metalNodesShader_geometry(realitykit::geometry_parameters params) {
    auto geo = params.geometry();
    float v0;
    v0 = 0.06;
    float v1;
    v1 = params.uniforms().time();
    float v2;
    v2 = 0.6;
    float v3;
    v3 = v1 * v2;
    float v4;
    v4 = sin(v3);
    float v5;
    v5 = v4 * v0;
    float3 v6;
    v6 = float3(0.0, v5, 0.0);
    geo.set_model_position_offset(v6);
}
