// metalNodesShader.swift — generated by MetalNodes. Pairs with metalNodesShader.metal.
//
// Add metalNodesShader.metal to the target so its functions land in the default library.
import RealityKit
import Metal

enum MetalNodesShaderMaterial {
    struct NoMetalDevice: Error {}

    /// Builds the material. Call once and reuse it — compiling shaders is not free.
    @MainActor
    static func make() throws -> CustomMaterial {
        guard let device = MTLCreateSystemDefaultDevice() else {
            throw NoMetalDevice()
        }
        let library = try device.makeDefaultLibrary(bundle: .main)
        let surface = CustomMaterial.SurfaceShader(named: "metalNodesShader_surface", in: library)
        let geometry = CustomMaterial.GeometryModifier(named: "metalNodesShader_geometry", in: library)
        return try CustomMaterial(surfaceShader: surface,
                                  geometryModifier: geometry,
                                  lightingModel: .lit)
    }

    /// A geometry modifier can push vertices outside the entity's original bounds,
    /// and RealityKit may then cull the entity. Grow the margin to cover the largest
    /// displacement your graph produces.
    @MainActor
    static func apply(to entity: ModelEntity, boundsMargin: Float = 0.5) throws {
        entity.model?.materials = [try make()]
        entity.model?.boundsMargin = boundsMargin
    }
}
