// stitchGroup.swift — generated by MetalNodes. Argument order matches stitchGroup.metal.
import SwiftUI

extension View {
    /// Applies the MetalNodes shader "stitchGroup".
    func stitchGroup(size: CGSize, time: Float, mouse: CGPoint, colorValue: Color, valueNoiseScale: Float, floatValue: Float) -> some View {
        colorEffect(ShaderLibrary.stitchGroup(
            .float2(size),
            .float(time),
            .float2(mouse),
            .color(colorValue),    // Color · Value
            .float(valueNoiseScale),    // Value Noise · Scale
            .float(floatValue)    // Float · Value
        ))
    }
}
